sudo: false
language: rust
rust:
- stable
env:
- RUST_BACKTRACE=full CARGO_INCREMENTAL=0
matrix:
  include:
  # test 32-bit
  - name: "i686-unknown-linux-musl"
    env: TARGET=i686-unknown-linux-musl RUST_BACKTRACE=full CARGO_INCREMENTAL=0
    addons:
      apt:
        packages:
        - gcc-multilib
        - musl-tools
  # test nightly channel
  - os: linux
    rust: nightly
os:
- linux
- osx
- windows

script: |
  if [[ "$TRAVIS_RUST_VERSION" == *stable* ]]; then
    rustup component add rustfmt; cargo fmt --version;
    cargo fmt -- --check || (echo "Please reformat your code with 'cargo fmt'
    (version $(cargo fmt --version))"; false);
  fi
  if [ -n "$TARGET" ]; then
    rustup target add "$TARGET" && cargo test --all --target "$TARGET"
  else
    cargo test --workspace && cargo test --workspace --all-targets
  fi
