[package]
name = "gfx_glyph"
version = "0.4.1"
authors = ["Alex Butler <alexheretic@gmail.com>"]
description = "Fast GPU cached text rendering using gfx-rs & rusttype"
repository = "https://github.com/alexheretic/gfx-glyph"
keywords = ["font", "ttf", "truetype", "gfx", "text"]
license = "Apache-2.0"
exclude = ["examples/*.ttf", "examples/*.txt", "benches/*.*"]
readme="README.md"

[dependencies]
log = "0.3"
rusttype = "0.2"
gfx = "0.16"
gfx_core = "0.7"
unicode-normalization = "0.1"
ordered-float = "0.5"
xi-unicode = "0.1.0"
linked-hash-map = "0.5"

[dev-dependencies]
pretty_env_logger = "0.1"
approx = "0.1"
gfx_window_glutin = "0.17"
glutin = "0.9"
time = "0.1"
cgmath = "0.15"
spin_sleep = "0.3"
lazy_static = "0.2"

[features]
# Compiles benchmark code, to be avoided normally as this currently requires nightly rust
bench = []
