[package]
name = "gfx_glyph"
version = "0.13.2"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2018"
description = "Fast GPU cached text rendering using gfx-rs & rusttype"
repository = "https://github.com/alexheretic/gfx-glyph"
keywords = ["font", "ttf", "truetype", "gfx", "text"]
license = "Apache-2.0"
readme="README.md"

[dependencies]
backtrace = "0.3"
gfx = "0.17"
gfx_core = "0.8"
glyph_brush = { version = "0.4", path = "../glyph-brush" }
log = "0.4"

[dev-dependencies]
env_logger = { version = "0.6", default-features = false }
approx = "0.3"
gfx_device_gl = "0.15.3"
gfx_window_glutin = "0.28"
glutin = "0.19"
cgmath = "0.17"
spin_sleep = "0.3"
