[package]
name = "gfx_glyph"
version = "0.16.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2018"
description = "Fast GPU cached text rendering using gfx-rs & rusttype"
repository = "https://github.com/alexheretic/gfx-glyph"
keywords = ["font", "ttf", "truetype", "gfx", "text"]
license = "Apache-2.0"
readme="README.md"

[dependencies]
backtrace = "0.3"
gfx = "0.18"
gfx_core = "0.9"
glyph_brush = { version = "0.6", path = "../glyph-brush" }
log = "0.4"

[dev-dependencies]
env_logger = { version = "0.7", default-features = false }
approx = "0.3"
glutin = "0.23"
old_school_gfx_glutin_ext = "0.23"
cgmath = "0.17"
spin_sleep = "0.3"
